name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: composer update
      run: composer update
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: vendor/bin/phpunit