name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/composer@v6
    - uses: php-actions/phpunit@v3
    - run: vendor/bin/phpunit