name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      uses: php-actions/composer@v6
        php-version: 8.2
    - run: vendor/bin/phpunit tests