name: PHPUnit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "latest"
    - uses: "ramsey/composer-install@v2"
      with:
        working-directory: "Fussball-Webapplikation/"
    - run: vendor/bin/phpunit tests